[package]
name = "jwt-decoder"
version = "0.1.0"
authors = ["Jean-Marcel Belmont <jbelmont@foodlogiq.com>"]

[dependencies]
base64 = "0.9.3"
serde_json = "1.0.30"
serde = "1.0.79"
serde_derive = "1.0.79"
chrono = "0.4.6"